WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/FindPositiveIngViewModel.cs
using ZadaniaRekrutacyjne.Utility;

namespace ZadaniaRekrutacyjne.Models
{
    public class FindPositiveIngViewModel
    {
        [IfNumberSplitedString]
        public string? numbersToCheck { get; set; }
    }
}

WebApplication1/Models/MatrixTaskViewModel.cs
using System.ComponentModel.DataAnnotations;
using WebApplication1.Utility;
using ZadaniaRekrutacyjne.Utility;

namespace ZadaniaRekrutacyjne.Models
{
    public class MatrixTaskViewModel
    {
        [IfMatrixIsCorrect]
        [IfNumberSplitedString]
        public string MatrixString { get; set; }
    }
}

WebApplication1/Models/MissingNumberViewModel.cs
using System.ComponentModel.DataAnnotations;
using WebApplication1.Utility;

namespace WebApplication1.Models
{
    public class MissingNumberViewModel
    {
        [IfStringIsNumber]
        public string MissingNumber { get; set; }
    }
}

WebApplication1/Controllers/FindTheSmallestPostivieIntigerController.cs
using Microsoft.AspNetCore.Mvc;
using ZadaniaRekrutacyjne.Models;
using ZadaniaRekrutacyjneBLL.Interfaces;
using ZadaniaRekrutacyjneBLL.Services;

namespace ZadaniaRekrutacyjne.Controllers
{
    public class FindTheSmallestPostivieIntigerController : Controller
    {
        private readonly IFindPositiveInt _findPositiveInt;
        public FindTheSmallestPostivieIntigerController(IFindPositiveInt findPositiveInt)
        {
               _findPositiveInt= findPositiveInt;
        }
        public IActionResult FindThePositiveInt()
        {
                return View();
        }
        [HttpPost]
        public IActionResult FindThePositiveInt(FindPositiveIngViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _findPositiveInt.FindPositiveIntiger(model.numbersToCheck);
                ViewBag.Model = result;
                return View(model);
            }
            else
            {
                return View();
            }
            
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Reflection;
using WebApplication1.Models;
using ZadaniaRekrutacyjne.Models;
using ZadaniaRekrutacyjneBLL.Interfaces;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMissingNumberService _missingNumberService;
        private readonly IFindHoleService _findHoleService;

        public HomeController(ILogger<HomeController> logger,IMissingNumberService missingNumberService, IFindHoleService findHoleService)
        {
            _missingNumberService = missingNumberService;
            _logger = logger;
            _findHoleService = findHoleService;
        }

        public IActionResult Index()
        {
                return View();
        }
        [HttpPost]
        public IActionResult Index(MissingNumberViewModel model)
        {   
            if (ModelState.IsValid)
            {
                var missingNumbers = _missingNumberService.FindMissingNumber(model.MissingNumber);
                ViewBag.Model = missingNumbers;
                return View(model);
            }
            else
            {
                return View();
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Controllers/MatrixTaskController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using ZadaniaRekrutacyjne.Models;
using ZadaniaRekrutacyjneBLL.Interfaces;
using ZadaniaRekrutacyjneBLL.Services;

namespace ZadaniaRekrutacyjne.Controllers
{
    public class MatrixTaskController : Controller
    {
        // GET: MatrixTaskController
        private readonly IFindHoleService _findHoleService;
        public MatrixTaskController(IFindHoleService findHoleService)
        {
            _findHoleService = findHoleService;
        }

        public ActionResult FindHole()
        {
                return View();
        }
        [HttpPost]
        public ActionResult FindHole(MatrixTaskViewModel model)
        {
            if (ModelState.IsValid)
            {
                var holes = _findHoleService.FindHole(model.MatrixString);
                ViewBag.Model = holes;
                return View(model);
            }
            else
            {
                return View();
            }
        }
    }
}

WebApplication1/Views/FindTheSmallestPostivieIntiger/FindThePositiveInt.cshtml
@model ZadaniaRekrutacyjne.Models.FindPositiveIngViewModel;
@{
}
<div class="input-container">
    <form asp-action="FindThePositiveInt" enctype="multipart/form-data">
        <div class="text-center">
            <h5>Podaj ciąg liczb ,aby znaleźć największą dodatnią liczbę którą nie podałeś :) oddziel liczby przecinkami</h5>
            <div class="row py-1">
                <input asp-for="numbersToCheck" placeholder="Input number..." class="form-control" />
                <span asp-validation-for="numbersToCheck" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-4 offset-4">
                    <button type="submit" class="btn btn-success form-control">Create</button>
                </div>
            </div>
        </div>
    </form>
    @if (ViewBag.Model != null)
    {
        <h5>Brakujące liczby to:</h5>
        <h6>@ViewBag.Model</h6>
    }
</div>

WebApplication1/Views/Home/FindHole.cshtml
@model ZadaniaRekrutacyjne.Models.FindHoleViewModel
@{

}
<style>
    .input-container {
        width: 40%;
        margin: 0 auto;
        margin-top: 100px;
        background-color: #ffffff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h5 {
        font-size: 20px;
        text-align: center;
        margin-top: 10px;
    }

    h6 {
        font-size: 15px;
        text-align: center;
        margin-top: 10px;
    }
</style>
<div class="input-container">
    <form asp-action="MatrixTask" enctype="multipart/form-data">
        <div class="text-center">
            <h5>Podaj liczbę kolumn macierzy</h5>
            <div class="row py-1">
                <input asp-for="MatrixColumns" placeholder="Input number..." class="form-control" />
                <span asp-validation-for="MatrixColumns" class="text-danger"></span>
            </div>
            <h5>Podaj liczbę wierszy macierzy</h5>
            <div class="row py-1">
                <input asp-for="MatrixRows" placeholder="Input number..." class="form-control" />
                <span asp-validation-for="MatrixRows" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-4 offset-4">
                    <button type="submit" class="btn btn-success form-control">Create</button>
                </div>
            </div>
        </div>
    </form>
</div>

WebApplication1/Views/Home/Index.cshtml
@model MissingNumberViewModel
@{
    ViewData["Title"] = "Home Page";
}
<div class="input-container">
    <form asp-action="Index" enctype="multipart/form-data">
    <div class="text-center">
        <h5>Podaj ciąg liczb ,który chcesz sprawdzić</h5>
        <div class="row py-1">
                <input asp-for="MissingNumber" placeholder="Input number..." class="form-control" />
            <span asp-validation-for="MissingNumber" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-4 offset-4">
                <button type="submit" class="btn btn-success form-control">Create</button>
            </div>
        </div>
    </div>
</form>
@if (ViewBag.Model != null)
{
    <h5>Brakujące liczby to:</h5>
    <h6>@ViewBag.Model</h6>
}
</div>

WebApplication1/Views/Home/MissingNumbers.cshtml
@model MissingNumberViewModel
<div class="input-container">
    <form asp-action="Index" enctype="multipart/form-data">
        <div class="text-center">
            <h5>Podaj ciąg liczb ,który chcesz sprawdzić</h5>
            <div class="row py-1">
                <input asp-for="MissingNumber" placeholder="Input number..." class="form-control" />
                <span asp-validation-for="MissingNumber" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-4 offset-4">
                    <button type="submit" class="btn btn-success form-control">Create</button>
                </div>
            </div>
        </div>
    </form>
    @if (ViewBag.Model != null)
    {
        <h5>Brakujące liczby to:</h5>
        <h6>@ViewBag.Model</h6>
    }
</div>

WebApplication1/Views/MatrixTask/FindHole.cshtml
@model ZadaniaRekrutacyjne.Models.MatrixTaskViewModel

<div class="input-container">
    <form asp-action="FindHole" enctype="multipart/form-data">
        <div class="text-center">
            <h5>Podaj macierz w postaci 101,100,111,101</h5>
            <div class="row py-1">
                <input asp-for="MatrixString" placeholder="Input number..." class="form-control" />
                <span asp-validation-for="MatrixString" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-4 offset-4">
                    <button type="submit" class="btn btn-success form-control">Create</button>
                </div>
            </div>
        </div>
    </form>
@if(ViewBag.Model!=null)
{
@foreach(var hole in ViewBag.Model)
{
    <h3>@hole</h3>
}
}
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Simple Sidebar - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/default.css")" media="screen" />
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom bg-light">Start Bootstrap</div>
            <div class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="" asp-controller="Home" asp-action="Index">Find Missing Numbers</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="" asp-controller="MatrixTask" asp-action="FindHole">Find Hole Task</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="" asp-controller="FindTheSmallestPostivieIntiger" asp-action="FindThePositiveInt">Find The Positive int</a>
            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <div class="container-fluid">
                    <button class="btn btn-primary" id="sidebarToggle">Toggle Menu</button>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                            <li class="nav-item active"><a class="nav-link" href="#!">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="#!">Link</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#!">Action</a>
                                    <a class="dropdown-item" href="#!">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#!">Something else here</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Zadania_na_rozmowy_rekrutacyjne - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

WebApplication1/Views/Shared/_MissingNumbers.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{

}